### ISSUE TITLE
does this package work?

### ISSUE THREAD

**Issue by jimmyff** [thosakwe/stripe_facade#1]
I'm following the JS documentation here:
https://stripe.com/docs/checkout#integration-custom

The first issue I'm getting is `Invalid argument(s): Attempt to pass Function 'Closure: (StripeTokenResponse) => dynamic' to JavaScript via without calling allowInterop or allowInteropCaptureThis`, when trying to set `token`, example code below:

```
    final stripe = StripeCheckout.configure(
      new StripeCheckoutOptions(
        key: 'pk_test_6pRNASCoBOKtIshFeQd4XMUh',
        image : 'https://stripe.com/img/documentation/checkout/marketplace.png',
        locale: 'auto',
        token: (StripeTokenResponse r) {
          // You can access the token ID with `token.id`.
          // Get the token ID to your server-side code for use.
        }
      )
    );

    stripe.open(
      new StripeCheckoutOptions(
        name: 'Test 123',
        description: 'product description',
        amount: 500
      )
    );

```
Is this an issue with the packages JS interop or do I need to use `allowInterop` in my code? When I remove the parameter token, then I get:
```
The method 'configure' was called on null.
Receiver: null
Tried calling: configure(Instance of 'JSObjectImpl')
```

Not sure if this package is working? Would be great to include an example folder or at least some information in the readme?

**Comment by thosakwe** [comment]
You need to use allowInterop on any Dart function when passed to a JS call.

**Comment by thosakwe** [comment]
We were able to resolve this in Gitter (Jimmy and I).

The solution: Include Stripe.js on your page.
