### ISSUE TITLE
Could we get an update?

### ISSUE THREAD

**Issue by jimmyff** [thosakwe/stripe_facade#2]
Hey, any chance you could update this package? The [source types](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/stripe) have been updated so it would be great to get the latest version. Thanks

**Comment by thosakwe** [comment]
I'm pretty busy today, so I might not necessarily be able to get this done.
However, if you'd like to submit a PR (use `dart_js_facade_gen` to generate the bindings), I'll happily merge. Thanks

**Comment by jimmyff** [comment]
submitted a PR!
